# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_object13 import InlineObject13  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineObject13(unittest.TestCase):
    """InlineObject13 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineObject13
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_object13.InlineObject13()  # noqa: E501
        if include_optional :
            return InlineObject13(
                permanent = True
            )
        else :
            return InlineObject13(
        )

    def testInlineObject13(self):
        """Test InlineObject13"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
