# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.schedule_node_status_monitoring_job_v1_api import ScheduleNodeStatusMonitoringJobV1Api  # noqa: E501
from openapi_client.rest import ApiException


class TestScheduleNodeStatusMonitoringJobV1Api(unittest.TestCase):
    """ScheduleNodeStatusMonitoringJobV1Api unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.schedule_node_status_monitoring_job_v1_api.ScheduleNodeStatusMonitoringJobV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_vaas_databases_dbname_node_status_delete(self):
        """Test case for v1_vaas_databases_dbname_node_status_delete

        """
        pass

    def test_v1_vaas_databases_dbname_node_status_get(self):
        """Test case for v1_vaas_databases_dbname_node_status_get

        """
        pass

    def test_v1_vaas_databases_dbname_node_status_put(self):
        """Test case for v1_vaas_databases_dbname_node_status_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
