# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.network_config_v1_api import NetworkConfigV1Api  # noqa: E501
from openapi_client.rest import ApiException


class TestNetworkConfigV1Api(unittest.TestCase):
    """NetworkConfigV1Api unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.network_config_v1_api.NetworkConfigV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_vaas_config_dbname_cidr_block_put(self):
        """Test case for v1_vaas_config_dbname_cidr_block_put

        """
        pass

    def test_v1_vaas_config_dbname_network_put(self):
        """Test case for v1_vaas_config_dbname_network_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
