# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.dc_graph_total_queries_per_hr_v1_api import DcGraphTotalQueriesPerHrV1Api  # noqa: E501
from openapi_client.rest import ApiException


class TestDcGraphTotalQueriesPerHrV1Api(unittest.TestCase):
    """DcGraphTotalQueriesPerHrV1Api unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.dc_graph_total_queries_per_hr_v1_api.DcGraphTotalQueriesPerHrV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_vaas_reports_dbname_query_by_hour_top5_users_post(self):
        """Test case for v1_vaas_reports_dbname_query_by_hour_top5_users_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
