# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.subcluster_host_detail_v1_api import SubclusterHostDetailV1Api  # noqa: E501
from openapi_client.rest import ApiException


class TestSubclusterHostDetailV1Api(unittest.TestCase):
    """SubclusterHostDetailV1Api unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.subcluster_host_detail_v1_api.SubclusterHostDetailV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_vaas_databases_database_name_subclusters_subcluster_name_hosts_host_id_delete(self):
        """Test case for v1_vaas_databases_database_name_subclusters_subcluster_name_hosts_host_id_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
