# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.schedule_auto_scaling_v1_api import ScheduleAutoScalingV1Api  # noqa: E501
from openapi_client.rest import ApiException


class TestScheduleAutoScalingV1Api(unittest.TestCase):
    """ScheduleAutoScalingV1Api unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.schedule_auto_scaling_v1_api.ScheduleAutoScalingV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_vaas_databases_dbname_auto_scaling_delete(self):
        """Test case for v1_vaas_databases_dbname_auto_scaling_delete

        """
        pass

    def test_v1_vaas_databases_dbname_auto_scaling_get(self):
        """Test case for v1_vaas_databases_dbname_auto_scaling_get

        """
        pass

    def test_v1_vaas_databases_dbname_auto_scaling_put(self):
        """Test case for v1_vaas_databases_dbname_auto_scaling_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
