# coding: utf-8

# flake8: noqa
"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.db_autoscaling_job_config import DBAutoscalingJobConfig
from openapi_client.models.db_autoscaling_job_config_subcluster import DBAutoscalingJobConfigSubcluster
from openapi_client.models.db_session_monitor_job_config import DBSessionMonitorJobConfig
from openapi_client.models.inline_object import InlineObject
from openapi_client.models.inline_object1 import InlineObject1
from openapi_client.models.inline_object10 import InlineObject10
from openapi_client.models.inline_object11 import InlineObject11
from openapi_client.models.inline_object12 import InlineObject12
from openapi_client.models.inline_object13 import InlineObject13
from openapi_client.models.inline_object14 import InlineObject14
from openapi_client.models.inline_object15 import InlineObject15
from openapi_client.models.inline_object16 import InlineObject16
from openapi_client.models.inline_object17 import InlineObject17
from openapi_client.models.inline_object18 import InlineObject18
from openapi_client.models.inline_object19 import InlineObject19
from openapi_client.models.inline_object2 import InlineObject2
from openapi_client.models.inline_object20 import InlineObject20
from openapi_client.models.inline_object21 import InlineObject21
from openapi_client.models.inline_object22 import InlineObject22
from openapi_client.models.inline_object23 import InlineObject23
from openapi_client.models.inline_object24 import InlineObject24
from openapi_client.models.inline_object25 import InlineObject25
from openapi_client.models.inline_object3 import InlineObject3
from openapi_client.models.inline_object4 import InlineObject4
from openapi_client.models.inline_object5 import InlineObject5
from openapi_client.models.inline_object6 import InlineObject6
from openapi_client.models.inline_object7 import InlineObject7
from openapi_client.models.inline_object8 import InlineObject8
from openapi_client.models.inline_object9 import InlineObject9
from openapi_client.models.inline_response200 import InlineResponse200
from openapi_client.models.inline_response2001 import InlineResponse2001
from openapi_client.models.inline_response2002 import InlineResponse2002
from openapi_client.models.inline_response404 import InlineResponse404
from openapi_client.models.inline_response428 import InlineResponse428
