# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class DBAutoscalingJobConfigSubcluster(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'vertica_subcluster_1_max_session': 'int',
        'vertica_subcluster_2_max_session': 'int',
        'vertica_subcluster_3_max_session': 'int'
    }

    attribute_map = {
        'vertica_subcluster_1_max_session': 'vertica_subcluster_1_max_session',
        'vertica_subcluster_2_max_session': 'vertica_subcluster_2_max_session',
        'vertica_subcluster_3_max_session': 'vertica_subcluster_3_max_session'
    }

    def __init__(self, vertica_subcluster_1_max_session=None, vertica_subcluster_2_max_session=None, vertica_subcluster_3_max_session=None, local_vars_configuration=None):  # noqa: E501
        """DBAutoscalingJobConfigSubcluster - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._vertica_subcluster_1_max_session = None
        self._vertica_subcluster_2_max_session = None
        self._vertica_subcluster_3_max_session = None
        self.discriminator = None

        self.vertica_subcluster_1_max_session = vertica_subcluster_1_max_session
        if vertica_subcluster_2_max_session is not None:
            self.vertica_subcluster_2_max_session = vertica_subcluster_2_max_session
        if vertica_subcluster_3_max_session is not None:
            self.vertica_subcluster_3_max_session = vertica_subcluster_3_max_session

    @property
    def vertica_subcluster_1_max_session(self):
        """Gets the vertica_subcluster_1_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501


        :return: The vertica_subcluster_1_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501
        :rtype: int
        """
        return self._vertica_subcluster_1_max_session

    @vertica_subcluster_1_max_session.setter
    def vertica_subcluster_1_max_session(self, vertica_subcluster_1_max_session):
        """Sets the vertica_subcluster_1_max_session of this DBAutoscalingJobConfigSubcluster.


        :param vertica_subcluster_1_max_session: The vertica_subcluster_1_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501
        :type vertica_subcluster_1_max_session: int
        """
        if self.local_vars_configuration.client_side_validation and vertica_subcluster_1_max_session is None:  # noqa: E501
            raise ValueError("Invalid value for `vertica_subcluster_1_max_session`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                vertica_subcluster_1_max_session is not None and vertica_subcluster_1_max_session < 1):  # noqa: E501
            raise ValueError("Invalid value for `vertica_subcluster_1_max_session`, must be a value greater than or equal to `1`")  # noqa: E501

        self._vertica_subcluster_1_max_session = vertica_subcluster_1_max_session

    @property
    def vertica_subcluster_2_max_session(self):
        """Gets the vertica_subcluster_2_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501


        :return: The vertica_subcluster_2_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501
        :rtype: int
        """
        return self._vertica_subcluster_2_max_session

    @vertica_subcluster_2_max_session.setter
    def vertica_subcluster_2_max_session(self, vertica_subcluster_2_max_session):
        """Sets the vertica_subcluster_2_max_session of this DBAutoscalingJobConfigSubcluster.


        :param vertica_subcluster_2_max_session: The vertica_subcluster_2_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501
        :type vertica_subcluster_2_max_session: int
        """
        if (self.local_vars_configuration.client_side_validation and
                vertica_subcluster_2_max_session is not None and vertica_subcluster_2_max_session < 1):  # noqa: E501
            raise ValueError("Invalid value for `vertica_subcluster_2_max_session`, must be a value greater than or equal to `1`")  # noqa: E501

        self._vertica_subcluster_2_max_session = vertica_subcluster_2_max_session

    @property
    def vertica_subcluster_3_max_session(self):
        """Gets the vertica_subcluster_3_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501


        :return: The vertica_subcluster_3_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501
        :rtype: int
        """
        return self._vertica_subcluster_3_max_session

    @vertica_subcluster_3_max_session.setter
    def vertica_subcluster_3_max_session(self, vertica_subcluster_3_max_session):
        """Sets the vertica_subcluster_3_max_session of this DBAutoscalingJobConfigSubcluster.


        :param vertica_subcluster_3_max_session: The vertica_subcluster_3_max_session of this DBAutoscalingJobConfigSubcluster.  # noqa: E501
        :type vertica_subcluster_3_max_session: int
        """
        if (self.local_vars_configuration.client_side_validation and
                vertica_subcluster_3_max_session is not None and vertica_subcluster_3_max_session < 1):  # noqa: E501
            raise ValueError("Invalid value for `vertica_subcluster_3_max_session`, must be a value greater than or equal to `1`")  # noqa: E501

        self._vertica_subcluster_3_max_session = vertica_subcluster_3_max_session

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DBAutoscalingJobConfigSubcluster):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DBAutoscalingJobConfigSubcluster):
            return True

        return self.to_dict() != other.to_dict()
