# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class DBAutoscalingJobConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'client_drain_time': 'int',
        'sequence_count': 'int',
        'subcluster': 'DBAutoscalingJobConfigSubcluster'
    }

    attribute_map = {
        'client_drain_time': 'client_drain_time',
        'sequence_count': 'sequence_count',
        'subcluster': 'subcluster'
    }

    def __init__(self, client_drain_time=None, sequence_count=None, subcluster=None, local_vars_configuration=None):  # noqa: E501
        """DBAutoscalingJobConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._client_drain_time = None
        self._sequence_count = None
        self._subcluster = None
        self.discriminator = None

        self.client_drain_time = client_drain_time
        self.sequence_count = sequence_count
        self.subcluster = subcluster

    @property
    def client_drain_time(self):
        """Gets the client_drain_time of this DBAutoscalingJobConfig.  # noqa: E501


        :return: The client_drain_time of this DBAutoscalingJobConfig.  # noqa: E501
        :rtype: int
        """
        return self._client_drain_time

    @client_drain_time.setter
    def client_drain_time(self, client_drain_time):
        """Sets the client_drain_time of this DBAutoscalingJobConfig.


        :param client_drain_time: The client_drain_time of this DBAutoscalingJobConfig.  # noqa: E501
        :type client_drain_time: int
        """
        if self.local_vars_configuration.client_side_validation and client_drain_time is None:  # noqa: E501
            raise ValueError("Invalid value for `client_drain_time`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                client_drain_time is not None and client_drain_time < 1):  # noqa: E501
            raise ValueError("Invalid value for `client_drain_time`, must be a value greater than or equal to `1`")  # noqa: E501

        self._client_drain_time = client_drain_time

    @property
    def sequence_count(self):
        """Gets the sequence_count of this DBAutoscalingJobConfig.  # noqa: E501


        :return: The sequence_count of this DBAutoscalingJobConfig.  # noqa: E501
        :rtype: int
        """
        return self._sequence_count

    @sequence_count.setter
    def sequence_count(self, sequence_count):
        """Sets the sequence_count of this DBAutoscalingJobConfig.


        :param sequence_count: The sequence_count of this DBAutoscalingJobConfig.  # noqa: E501
        :type sequence_count: int
        """
        if self.local_vars_configuration.client_side_validation and sequence_count is None:  # noqa: E501
            raise ValueError("Invalid value for `sequence_count`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                sequence_count is not None and sequence_count < 1):  # noqa: E501
            raise ValueError("Invalid value for `sequence_count`, must be a value greater than or equal to `1`")  # noqa: E501

        self._sequence_count = sequence_count

    @property
    def subcluster(self):
        """Gets the subcluster of this DBAutoscalingJobConfig.  # noqa: E501


        :return: The subcluster of this DBAutoscalingJobConfig.  # noqa: E501
        :rtype: DBAutoscalingJobConfigSubcluster
        """
        return self._subcluster

    @subcluster.setter
    def subcluster(self, subcluster):
        """Sets the subcluster of this DBAutoscalingJobConfig.


        :param subcluster: The subcluster of this DBAutoscalingJobConfig.  # noqa: E501
        :type subcluster: DBAutoscalingJobConfigSubcluster
        """
        if self.local_vars_configuration.client_side_validation and subcluster is None:  # noqa: E501
            raise ValueError("Invalid value for `subcluster`, must not be `None`")  # noqa: E501

        self._subcluster = subcluster

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DBAutoscalingJobConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DBAutoscalingJobConfig):
            return True

        return self.to_dict() != other.to_dict()
