# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class DBSessionMonitorJobConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'shutdown_timeout': 'str'
    }

    attribute_map = {
        'shutdown_timeout': 'shutdown_timeout'
    }

    def __init__(self, shutdown_timeout=None, local_vars_configuration=None):  # noqa: E501
        """DBSessionMonitorJobConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._shutdown_timeout = None
        self.discriminator = None

        self.shutdown_timeout = shutdown_timeout

    @property
    def shutdown_timeout(self):
        """Gets the shutdown_timeout of this DBSessionMonitorJobConfig.  # noqa: E501


        :return: The shutdown_timeout of this DBSessionMonitorJobConfig.  # noqa: E501
        :rtype: str
        """
        return self._shutdown_timeout

    @shutdown_timeout.setter
    def shutdown_timeout(self, shutdown_timeout):
        """Sets the shutdown_timeout of this DBSessionMonitorJobConfig.


        :param shutdown_timeout: The shutdown_timeout of this DBSessionMonitorJobConfig.  # noqa: E501
        :type shutdown_timeout: str
        """
        if self.local_vars_configuration.client_side_validation and shutdown_timeout is None:  # noqa: E501
            raise ValueError("Invalid value for `shutdown_timeout`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                shutdown_timeout is not None and len(shutdown_timeout) > 8):
            raise ValueError("Invalid value for `shutdown_timeout`, length must be less than or equal to `8`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                shutdown_timeout is not None and not re.search(r'([0-9][0-9]\:[0-9][0-9]\:[0-9][0-9])', shutdown_timeout)):  # noqa: E501
            raise ValueError(r"Invalid value for `shutdown_timeout`, must be a follow pattern or equal to `/([0-9][0-9]\:[0-9][0-9]\:[0-9][0-9])/`")  # noqa: E501

        self._shutdown_timeout = shutdown_timeout

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DBSessionMonitorJobConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DBSessionMonitorJobConfig):
            return True

        return self.to_dict() != other.to_dict()
