# coding: utf-8

"""
    VAAS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class InlineObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cloud_storage_backup_path': 'str',
        'restore_point_limit': 'int'
    }

    attribute_map = {
        'cloud_storage_backup_path': 'cloud_storage_backup_path',
        'restore_point_limit': 'restore_point_limit'
    }

    def __init__(self, cloud_storage_backup_path=None, restore_point_limit=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cloud_storage_backup_path = None
        self._restore_point_limit = None
        self.discriminator = None

        self.cloud_storage_backup_path = cloud_storage_backup_path
        self.restore_point_limit = restore_point_limit

    @property
    def cloud_storage_backup_path(self):
        """Gets the cloud_storage_backup_path of this InlineObject.  # noqa: E501


        :return: The cloud_storage_backup_path of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._cloud_storage_backup_path

    @cloud_storage_backup_path.setter
    def cloud_storage_backup_path(self, cloud_storage_backup_path):
        """Sets the cloud_storage_backup_path of this InlineObject.


        :param cloud_storage_backup_path: The cloud_storage_backup_path of this InlineObject.  # noqa: E501
        :type cloud_storage_backup_path: str
        """
        if self.local_vars_configuration.client_side_validation and cloud_storage_backup_path is None:  # noqa: E501
            raise ValueError("Invalid value for `cloud_storage_backup_path`, must not be `None`")  # noqa: E501

        self._cloud_storage_backup_path = cloud_storage_backup_path

    @property
    def restore_point_limit(self):
        """Gets the restore_point_limit of this InlineObject.  # noqa: E501


        :return: The restore_point_limit of this InlineObject.  # noqa: E501
        :rtype: int
        """
        return self._restore_point_limit

    @restore_point_limit.setter
    def restore_point_limit(self, restore_point_limit):
        """Sets the restore_point_limit of this InlineObject.


        :param restore_point_limit: The restore_point_limit of this InlineObject.  # noqa: E501
        :type restore_point_limit: int
        """
        if self.local_vars_configuration.client_side_validation and restore_point_limit is None:  # noqa: E501
            raise ValueError("Invalid value for `restore_point_limit`, must not be `None`")  # noqa: E501

        self._restore_point_limit = restore_point_limit

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject):
            return True

        return self.to_dict() != other.to_dict()
